const buttonA = new jacdac.ButtonHost("B")
const buttonB = new jacdac.ButtonHost("B")
const buttonC = new jacdac.ButtonHost("C")
const buttonD = new jacdac.ButtonHost("D")
buttonA.start()
buttonB.start()
buttonC.start()
buttonD.start()
